# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CCWeibo' do
pod 'Alamofire'
pod 'Kingfisher'
pod 'MBProgressHUD'
pod 'SwiftyJSON'
pod 'Reveal-iOS-SDK', :configurations => ['Debug']
pod 'SnapKit'
end

target 'CCWeiboTests' do

end

target 'CCWeiboUITests' do

end

