# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CCWeibo' do
pod 'Alamofire', '~> 3.0'
pod 'Kingfisher', '~> 2.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

target 'CCWeiboTests' do

end

target 'CCWeiboUITests' do

end

